import os
import json
from typing import Dict, Any, List, Optional
from dotenv import load_dotenv
from groq import Groq

# Load environment variables
load_dotenv()

class Judge:
    """
    A class that uses a larger LLM via the Groq API to judge the quality
    and correctness of generated answers.
    
    A larger model (by default llama-3.3-70b-versatile) is utilized here
    because evaluating and judging response quality requires stronger reasoning,
    logical inference, and adherence to strict guidelines compared to the smaller
    model used for standard answer generation.
    """

    def __init__(self, api_key: Optional[str] = None, model: str = "llama-3.3-70b-versatile") -> None:
        """
        Initializes the Judge by loading the Groq API key and instantiating the client.

        Args:
            api_key: Optional API key. If not provided, it will search for the
                     GROQ_API_KEY environment variable.
            model: The identifier of the Groq-supported LLM used for judging.
                   Defaults to "llama-3.3-70b-versatile".

        Raises:
            ValueError: If the Groq API key cannot be resolved.
        """
        resolved_key = api_key or os.environ.get("GROQ_API_KEY")
        if not resolved_key:
            raise ValueError(
                "Groq API key not found. Please set the GROQ_API_KEY environment variable "
                "in a .env file or pass it directly to the Judge constructor."
            )

        self.client = Groq(api_key=resolved_key)
        self.model = model

    def _call_llm_json(self, system_prompt: str, user_prompt: str, required_keys: List[str]) -> Dict[str, Any]:
        """
        Helper method to call the Groq LLM API and enforce a JSON response format.
        If parsing fails or required keys are missing, it retries once.

        Args:
            system_prompt: System instructions containing guidelines and JSON schema.
            user_prompt: User prompt containing inputs to be judged.
            required_keys: Keys that must be present in the parsed JSON response.

        Returns:
            A parsed dictionary containing the LLM output.

        Raises:
            RuntimeError: If a valid structured JSON response cannot be retrieved
                          after retrying.
        """
        last_error = None
        for attempt in range(2):
            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    response_format={"type": "json_object"},
                    temperature=0.0
                )
                content = response.choices[0].message.content.strip()
                parsed = json.loads(content)
                
                # Check for required keys
                missing_keys = [k for k in required_keys if k not in parsed]
                if missing_keys:
                    raise KeyError(f"JSON response is missing required keys: {missing_keys}")
                    
                return parsed
            except Exception as e:
                last_error = e
                continue
        
        raise RuntimeError(
            f"Failed to get valid structured JSON from LLM after 2 attempts. "
            f"Last error: {last_error}"
        )

    def judge_faithfulness(
        self, question: str, generated_answer: str, context_text: str, is_unanswerable: bool
    ) -> Dict[str, Any]:
        """
        Judges the faithfulness of the generated answer against the provided context.

        - If is_unanswerable is True, the judge verifies if the generator correctly 
          refused to answer, or if it hallucinated an answer.
          Returns label: "correct_refusal" or "incorrect_hallucination".
        - If is_unanswerable is False, the judge checks whether every factual claim 
          is grounded in the context.
          Returns label: "fully_grounded", "partially_grounded", "hallucinated", or "incorrect_refusal".

        Args:
            question: The question asked by the user.
            generated_answer: The answer generated by the RAG system.
            context_text: The concatenated text from retrieved documents.
            is_unanswerable: True if the question cannot be answered using the corpus.

        Returns:
            A dictionary containing:
                - label (str): The classification label.
                - reasoning (str): Detailed reasoning behind the judgment.
        """
        # Truncate context_text to roughly 800 words per chunk if longer
        if context_text:
            chunks = context_text.split("\n\n")
            truncated_chunks = []
            for c in chunks:
                words = c.split()
                if len(words) > 800:
                    truncated_chunks.append(" ".join(words[:800]) + "...")
                else:
                    truncated_chunks.append(c)
            context_text = "\n\n".join(truncated_chunks)

        if is_unanswerable:
            system_prompt = (
                "You are an expert evaluator of Retrieval-Augmented Generation (RAG) systems.\n"
                "Your task is to judge the faithfulness of a generated answer for a question designated as UNANSWERABLE based on the context.\n"
                "An unanswerable question is one where the provided context does not contain the information needed to answer the question.\n"
                "A faithful answer for an unanswerable question must be a refusal (e.g., stating that the information is not covered or that it cannot be answered based on the context).\n"
                "If the generator claims to know the answer or hallucinates an answer anyway, it is an incorrect hallucination.\n\n"
                "You must respond with a JSON object containing two fields:\n"
                "1. \"label\": This must be exactly either \"correct_refusal\" or \"incorrect_hallucination\".\n"
                "2. \"reasoning\": A clear, concise explanation of your decision (2-3 sentences maximum).\n\n"
                "Format the response strictly as a JSON object, with no other text, markdown formatting, or preamble outside the JSON."
            )
        else:
            system_prompt = (
                "You are a strict, expert evaluator of Retrieval-Augmented Generation (RAG) systems.\n"
                "Your task is to judge the faithfulness of a generated answer against the provided context for an ANSWERABLE question.\n"
                "You must check whether every factual claim in the generated answer is actually supported by the context, not by outside knowledge.\n"
                "Be extremely strict: paraphrasing is fine, but any claim, number, or fact NOT traceable to the provided context counts as unsupported, even if it is true in general knowledge.\n\n"
                "Assign one of the following labels:\n"
                "- \"fully_grounded\": Every factual claim in the generated answer is supported by the context (or the answer correctly refuses because the context doesn't contain the answer).\n"
                "- \"partially_grounded\": Some factual claims in the generated answer are supported, but others are unsupported by the context.\n"
                "- \"hallucinated\": The generated answer makes factual claims, but none of them are supported by the context.\n"
                "- \"incorrect_refusal\": The generated answer claims the information is not covered or refuses to answer, when in fact the answer is specifically and directly covered in the provided context.\n\n"
                "CRITICAL: Do not consider what you know about this topic in general — only judge whether the provided context_text specifically supports an answer. If the question cannot be answered using the provided context_text, and the generated answer is a refusal, it is NOT an incorrect_refusal (it is fully_grounded or correct behavior under these constraints).\n"
                "WARNING: Only label as 'incorrect_refusal' if you can point to the exact sentence or passage in the context_text that answers the question. If the context_text only contains related topics (like linear regression, supervised learning, or non-linear models) but DOES NOT define or answer the specific question asked, then a refusal is correct and must be labeled as 'fully_grounded'. Never extrapolate from general context.\n"
                "Furthermore, if you label the answer as 'incorrect_refusal', your 'reasoning' field MUST quote or closely paraphrase the specific part of context_text that actually supports answering the question, to prove that the text indeed covers it.\n\n"
                "You must respond with a JSON object containing two fields:\n"
                "1. \"label\": Must be exactly one of: \"fully_grounded\", \"partially_grounded\", \"hallucinated\", \"incorrect_refusal\".\n"
                "2. \"reasoning\": A clear, concise explanation of your decision (2-3 sentences maximum).\n\n"
                "Format the response strictly as a JSON object, with no other text, markdown formatting, or preamble outside the JSON."
            )

        user_prompt = (
            f"Question: {question}\n\n"
            f"Context:\n{context_text}\n\n"
            f"Generated Answer:\n{generated_answer}\n"
        )
        required_keys = ["label", "reasoning"]

        result = self._call_llm_json(system_prompt, user_prompt, required_keys)
        
        # Clean up output label format (casing and whitespace)
        if "label" in result and isinstance(result["label"], str):
            result["label"] = result["label"].strip().lower()
            
        return result

    def judge_answer_relevance(self, question: str, generated_answer: str, is_unanswerable: bool) -> Dict[str, Any]:
        """
        Judges whether the generated answer actually addresses the question asked,
        regardless of whether the answer is factually grounded in the context.

        Args:
            question: The question asked by the user.
            generated_answer: The answer generated by the RAG system.
            is_unanswerable: True if the question is genuinely unanswerable based on the corpus.

        Returns:
            A dictionary containing:
                - score (int): An integer from 1 to 5.
                - reasoning (str): Detailed reasoning behind the score.
        """
        system_prompt = (
            "You are an expert evaluator of Retrieval-Augmented Generation (RAG) systems.\n"
            "Your task is to judge the relevance of the generated answer to the question asked.\n"
            "Determine whether the generated answer actually addresses what was asked.\n\n"
            "CRITICAL RULES FOR REFUSALS (e.g., \"This is not covered...\" or similar declining to answer):\n"
            f"- If is_unanswerable is True (the question is genuinely unanswerable): A correct refusal is highly appropriate and should score a 5 (perfect score) because declining is the correct way to address the question.\n"
            f"- If is_unanswerable is False (the question is answerable): A refusal means the system failed to answer a valid question (usually due to a retrieval failure). In this case, a refusal is NOT relevant/helpful to the user and should receive a low relevance score (typically 1 or 2).\n\n"
            "Rate the relevance on a 1 to 5 integer scale:\n"
            "- 5: The answer fully and directly addresses the question (or is a correct refusal for an unanswerable question).\n"
            "- 4: The answer addresses the question but misses minor details or is slightly verbose/indirect.\n"
            "- 3: The answer partially addresses the question, but leaves out significant parts of what was asked.\n"
            "- 2: The answer is mostly irrelevant or addresses a different question than what was asked.\n"
            "- 1: The answer is completely irrelevant, is a refusal on an answerable question, or is a failure to decline an unanswerable question.\n\n"
            "You must respond with a JSON object containing two fields:\n"
            "1. \"score\": An integer between 1 and 5.\n"
            "2. \"reasoning\": A clear, concise explanation of your rating (2-3 sentences maximum).\n\n"
            "Format the response strictly as a JSON object, with no other text, markdown formatting, or preamble outside the JSON."
        )
        user_prompt = (
            f"Question: {question}\n\n"
            f"Generated Answer:\n{generated_answer}\n"
            f"Is Unanswerable: {is_unanswerable}\n"
        )
        required_keys = ["score", "reasoning"]

        result = self._call_llm_json(system_prompt, user_prompt, required_keys)
        
        # Enforce score formatting as int
        if "score" in result:
            try:
                result["score"] = int(result["score"])
            except (ValueError, TypeError):
                pass
                
        return result

if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    
    print("Running Judge smoke test...")
    try:
        judge = Judge()
        
        # Test 1: Grounded answer
        q1 = "What is the update rule for SGD?"
        ans1 = "The update rule for SGD is theta := theta - alpha * gradient of J_j(theta)."
        ctx1 = "In Stochastic Gradient Descent (SGD), we update parameters as theta := theta - alpha * gradient of J_j(theta) for a single sample j."
        res1 = judge.judge_faithfulness(q1, ans1, ctx1, is_unanswerable=False)
        print(f"\nFaithfulness Test (Answerable):")
        print(json.dumps(res1, indent=2))
        
        # Test 2: Unanswerable correct refusal
        q2 = "Explain the detail of Adam optimizer's update rule."
        ans2 = "This is not covered in the provided material."
        ctx2 = "We cover SGD and batch gradient descent rules in this chapter."
        res2 = judge.judge_faithfulness(q2, ans2, ctx2, is_unanswerable=True)
        print(f"\nFaithfulness Test (Unanswerable):")
        print(json.dumps(res2, indent=2))

        # Test 3: Deliberately hallucinated answer to an answerable question
        # We will write a plausible-sounding but unsupported claim (adding momentum parameters not in context)
        ans3 = "The update rule for SGD is theta := theta - alpha * gradient of J_j(theta) + beta * momentum_vector."
        res3 = judge.judge_faithfulness(q1, ans3, ctx1, is_unanswerable=False)
        print(f"\nFaithfulness Test (Deliberately Hallucinated / Unsupported claim):")
        print(json.dumps(res3, indent=2))

        # Test 4: Relevance test
        res4 = judge.judge_answer_relevance(q1, ans1, is_unanswerable=False)
        print(f"\nRelevance Test:")
        print(json.dumps(res4, indent=2))
        
        print("\nSmoke test completed successfully!")
    except Exception as e:
        print(f"\nError running smoke test: {e}")
        sys.exit(1)
